const posts = [
  {
    id: 1001,
    author: 1,
    category: [1, 2],
    tags: [3, 4],
    title: "Título post mil, prueba. Animales",
    subTitle: "Este es un subtítulo",
    date: "2023-03-28T18:12:27",
    content: `<img src="https://placeimg.com/800/400/animals" alt="animales"/><p>Animalitos. \nEste es el texto en un párrafo, con varias líneas salteadas por barras invertidas y letra n. \nLorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas nemo itaque cum debitis quo, est quisquam obcaecati asperiores a? Fugiat, eum ipsum temporibus consequatur ab omnis tenetur minima nam labore? y muchos más Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse nulla voluptatum nesciunt consectetur temporibus officia aliquam deleniti eaque, rerum aliquid vitae modi illum inventore cum qui expedita et eveniet quam?\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto pariatur facilis maxime illo eligendi, non est quidem, magnam, deserunt praesentium ab obcaecati sit omnis voluptas cum placeat ad beatae eaque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, incidunt quae consequatur esse fugit eos deleniti dignissimos dolores modi voluptas, ducimus provident autem ut nihil odit at ratione. Ullam, maxime! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo maxime vel ex explicabo! Ullam, excepturi sed quis quaerat dolor culpa fugit earum quod dolorum hic perferendis totam atque quos labore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia aperiam repudiandae, quaerat aspernatur, itaque et odio quas ducimus voluptas corporis illo quia rem labore deserunt? Reiciendis porro repellat vitae nisi. \nLorem ipsum dolor, sit amet consectetur adipisicing elit. Modi, id. Laudantium molestias ipsum iure corrupti voluptate quas autem cumque? Aperiam adipisci illum quibusdam corporis culpa optio possimus temporibus aut accusantium!</p>`,
  },
  {
    id: 1002,
    author: 1,
    category: [1, 2],
    tags: [3, 4],
    title: "Segundo post, seguimos probando",
    subTitle: "Este es un subtítulo de prueba dos",
    date: "2023-03-28T19:12:27",
    content: `<img src="https://placeimg.com/800/400/tech" alt="tech"/><p>Segundo texto. \nEste es el texto en un párrafo, con varias líneas salteadas por barras invertidas y letra n. \nLorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas nemo itaque cum debitis quo, est quisquam obcaecati asperiores a? Fugiat, eum ipsum temporibus consequatur ab omnis tenetur minima nam labore? y muchos más Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse nulla voluptatum nesciunt consectetur temporibus officia aliquam deleniti eaque, rerum aliquid vitae modi illum inventore cum qui expedita et eveniet quam?\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto pariatur facilis maxime illo eligendi, non est quidem, magnam, deserunt praesentium ab obcaecati sit omnis voluptas cum placeat ad beatae eaque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, incidunt quae consequatur esse fugit eos deleniti dignissimos dolores modi voluptas, ducimus provident autem ut nihil odit at ratione. Ullam, maxime! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo maxime vel ex explicabo! Ullam, excepturi sed quis quaerat dolor culpa fugit earum quod dolorum hic perferendis totam atque quos labore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia aperiam repudiandae, quaerat aspernatur, itaque et odio quas ducimus voluptas corporis illo quia rem labore deserunt? Reiciendis porro repellat vitae nisi. \nLorem ipsum dolor, sit amet consectetur adipisicing elit. Modi, id. Laudantium molestias ipsum iure corrupti voluptate quas autem cumque? Aperiam adipisci illum quibusdam corporis culpa optio possimus temporibus aut accusantium!</p>`,
  },
  {
    id: 1003,
    author: 1,
    category: [1, 2],
    tags: [3, 4],
    title: "Tercer post, veamos como quedan varios, Título post mil, prueba",
    subTitle: "Este es un subtítulo",
    date: "2023-03-28T18:12:27",
    content: `<img src="https://placeimg.com/800/400/people" alt="gentes"/><p>Gentes, tecer tesssto. \nEste es el texto en un párrafo, con varias líneas salteadas por barras invertidas y letra n. \nLorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas nemo itaque cum debitis quo, est quisquam obcaecati asperiores a? Fugiat, eum ipsum temporibus consequatur ab omnis tenetur minima nam labore? y muchos más Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse nulla voluptatum nesciunt consectetur temporibus officia aliquam deleniti eaque, rerum aliquid vitae modi illum inventore cum qui expedita et eveniet quam?\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto pariatur facilis maxime illo eligendi, non est quidem, magnam, deserunt praesentium ab obcaecati sit omnis voluptas cum placeat ad beatae eaque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, incidunt quae consequatur esse fugit eos deleniti dignissimos dolores modi voluptas, ducimus provident autem ut nihil odit at ratione. Ullam, maxime! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo maxime vel ex explicabo! Ullam, excepturi sed quis quaerat dolor culpa fugit earum quod dolorum hic perferendis totam atque quos labore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia aperiam repudiandae, quaerat aspernatur, itaque et odio quas ducimus voluptas corporis illo quia rem labore deserunt? Reiciendis porro repellat vitae nisi. \nLorem ipsum dolor, sit amet consectetur adipisicing elit. Modi, id. Laudantium molestias ipsum iure corrupti voluptate quas autem cumque? Aperiam adipisci illum quibusdam corporis culpa optio possimus temporibus aut accusantium!</p>`,
  },
  {
    id: 1004,
    author: 1,
    category: [1, 2],
    tags: [3, 4],
    title: "4to Cuarto - IV - post milcuatro, prueba",
    subTitle: "Este es un subtítulo",
    date: "2023-03-28T18:12:27",
    content: `<img src="https://placeimg.com/800/400/arch" alt="arqui"/><p>-Cuarto texto, arqui. \nEste es el texto en un párrafo, con varias líneas salteadas por barras invertidas y letra n. \nLorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas nemo itaque cum debitis quo, est quisquam obcaecati asperiores a? Fugiat, eum ipsum temporibus consequatur ab omnis tenetur minima nam labore? y muchos más Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse nulla voluptatum nesciunt consectetur temporibus officia aliquam deleniti eaque, rerum aliquid vitae modi illum inventore cum qui expedita et eveniet quam?\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto pariatur facilis maxime illo eligendi, non est quidem, magnam, deserunt praesentium ab obcaecati sit omnis voluptas cum placeat ad beatae eaque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, incidunt quae consequatur esse fugit eos deleniti dignissimos dolores modi voluptas, ducimus provident autem ut nihil odit at ratione. Ullam, maxime! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo maxime vel ex explicabo! Ullam, excepturi sed quis quaerat dolor culpa fugit earum quod dolorum hic perferendis totam atque quos labore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia aperiam repudiandae, quaerat aspernatur, itaque et odio quas ducimus voluptas corporis illo quia rem labore deserunt? Reiciendis porro repellat vitae nisi. \nLorem ipsum dolor, sit amet consectetur adipisicing elit. Modi, id. Laudantium molestias ipsum iure corrupti voluptate quas autem cumque? Aperiam adipisci illum quibusdam corporis culpa optio possimus temporibus aut accusantium!</p>`,
  },
  {
    id: 1005,
    author: 1,
    category: [1, 2],
    tags: [3, 4],
    title: "Quinto título post mil, prueba",
    subTitle: "Este es un subtítulo",
    date: "2023-03-28T22:12:27",
    content: `<img src="https://placeimg.com/800/400/arch" alt="arqui"/><p>-Cuarto texto, arqui. \nEste es el texto en un párrafo, con varias líneas salteadas por barras invertidas y letra n. \nLorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas nemo itaque cum debitis quo, est quisquam obcaecati asperiores a? Fugiat, eum ipsum temporibus consequatur ab omnis tenetur minima nam labore? y muchos más Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse nulla voluptatum nesciunt consectetur temporibus officia aliquam deleniti eaque, rerum aliquid vitae modi illum inventore cum qui expedita et eveniet quam?\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto pariatur facilis maxime illo eligendi, non est quidem, magnam, deserunt praesentium ab obcaecati sit omnis voluptas cum placeat ad beatae eaque! Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium, incidunt quae consequatur esse fugit eos deleniti dignissimos dolores modi voluptas, ducimus provident autem ut nihil odit at ratione. Ullam, maxime! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo maxime vel ex explicabo! Ullam, excepturi sed quis quaerat dolor culpa fugit earum quod dolorum hic perferendis totam atque quos labore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia aperiam repudiandae, quaerat aspernatur, itaque et odio quas ducimus voluptas corporis illo quia rem labore deserunt? Reiciendis porro repellat vitae nisi. \nLorem ipsum dolor, sit amet consectetur adipisicing elit. Modi, id. Laudantium molestias ipsum iure corrupti voluptate quas autem cumque? Aperiam adipisci illum quibusdam corporis culpa optio possimus temporibus aut accusantium!</p>`,
  },
];

export default posts;
